using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ZVec.Extensions.VectorData.SourceGenerator;

public sealed partial class ZVecRecordMetadataGenerator
{
    private static void GenerateSource(SourceProductionContext context, RecordModel model)
    {
        var propertiesList = new StringBuilder();
        if (model.KeyProp.HasValue)
        {
            propertiesList.AppendLine($"            new VectorStoreKeyProperty(\"{model.KeyProp.Value.Name}\", typeof({model.KeyProp.Value.FullyQualifiedType})),");
        }

        if (model.VectorProp.HasValue)
        {
            propertiesList.AppendLine($"            new VectorStoreVectorProperty(\"{model.VectorProp.Value.Name}\", typeof({model.VectorProp.Value.FullyQualifiedType}), {model.VectorProp.Value.VectorDimensions}),");
        }

        foreach (var dataProp in model.DataProps)
        {
            propertiesList.AppendLine($"            new VectorStoreDataProperty(\"{dataProp.Name}\", typeof({dataProp.FullyQualifiedType}))");
            if (dataProp.IsIndexed || dataProp.IsFullTextIndexed)
            {
                propertiesList.Append(" { ");
                if (dataProp.IsIndexed)
                {
                    propertiesList.Append("IsIndexed = true");
                }

                if (dataProp.IsFullTextIndexed)
                {
                    if (dataProp.IsIndexed)
                    {
                        propertiesList.Append(", ");
                    }

                    propertiesList.Append("IsFullTextIndexed = true");
                }

                propertiesList.Append(" }");
            }

            propertiesList.AppendLine(",");
        }

        string schemaBuilderBody = BuildSchemaBuilderBody(model);
        string toDocBody = BuildToDocBody(model);
        string fromDocBody = BuildFromDocBody(model);

        string source = $$"""
// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Microsoft.Extensions.VectorData;
using ZVec.Extensions.VectorData.Mapping;
using ZVec.NET;
using ZVec.NET.Mapping;

namespace {{model.NamespaceName}};

/// <summary>
/// Generated zero-reflection static metadata mapper and schema factory for <see cref="{{model.ClassName}}"/>.
/// </summary>
public static class {{model.ClassName}}{{GeneratorMetadataNames.GeneratedMapperSuffix}}
{
    /// <summary>Generated collection definition.</summary>
    public static VectorStoreCollectionDefinition Definition { get; } = new VectorStoreCollectionDefinition
    {
        Properties = new VectorStoreProperty[]
        {
{{propertiesList.ToString().TrimEnd()}}
        }
    };

    /// <summary>
    /// Builds a native <see cref="ZVecCollectionSchema"/> without reflection using <see cref="ZVecCollectionSchemaBuilder"/>.
    /// </summary>
    public static ZVecCollectionSchema BuildSchema(string collectionName)
    {
        var builder = new ZVecCollectionSchemaBuilder(collectionName);
{{schemaBuilderBody}}
        return builder.Build();
    }

    /// <summary>Zero-reflection mapper for {{model.ClassName}}.</summary>
    public sealed class Mapper : IZVecRecordMapper<{{model.ClassName}}>
    {
        /// <inheritdoc />
        public ZVecDoc ToDoc({{model.ClassName}} record, ZVecTypeModel model)
        {
            if (record == null) throw new ArgumentNullException(nameof(record));
            _ = model;
{{toDocBody}}
        }

        /// <inheritdoc />
        public {{model.ClassName}} FromDoc(ZVecDoc doc, ZVecTypeModel model)
        {
            if (doc == null) throw new ArgumentNullException(nameof(doc));
            _ = model;
            var record = new {{model.ClassName}}();
{{fromDocBody}}
            return record;
        }
    }

    internal static class {{model.ClassName}}MapperRegistration
    {
        [ModuleInitializer]
        internal static void Register()
        {
            ZVecRecordMapperRegistry.Register<{{model.ClassName}}>(new Mapper());
            ZVecCollectionSchemaRegistry.Register<{{model.ClassName}}>(BuildSchema, Definition);
        }
    }
}
""";

        string hintName = $"{model.NamespaceName.Replace('.', '_')}_{model.ClassName}{GeneratorMetadataNames.GeneratedMapperSuffix}.g.cs";
        context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
    }

    private static string BuildSchemaBuilderBody(RecordModel model)
    {
        var lines = new StringBuilder();

        foreach (var dataProp in model.DataProps)
        {
            if (dataProp.IsFullTextIndexed &&
                dataProp.FullyQualifiedType is GeneratorMetadataNames.GlobalSystemStringType
                    or GeneratorMetadataNames.StringTypeAlias)
            {
                lines.AppendLine($$"""        builder.AddVector(new ZVecVectorSchema { Name = "{{dataProp.StorageName}}", DataType = ZVecDataType.String, Dimension = 0, IndexParam = {{GeneratorMetadataNames.FtsIndexParamExpression}} });""");
            }
            else
            {
                string dataType = MapSpecialTypeToZVecDataType(dataProp.SpecialType, dataProp.FullyQualifiedType);
                string invertParam = dataProp.IsIndexed
                    ? GeneratorMetadataNames.InvertIndexParamExpression
                    : GeneratorMetadataNames.NullLiteral;
                lines.AppendLine($"        builder.AddField(\"{dataProp.StorageName}\", {dataType}, true, {invertParam});");
            }
        }

        if (model.VectorProp.HasValue)
        {
            var vector = model.VectorProp.Value;
            lines.AppendLine($"        builder.AddVector(\"{vector.StorageName}\", ZVecDataType.VectorFp32, {vector.VectorDimensions}, {GeneratorMetadataNames.HnswIndexParamExpression});");
        }

        return lines.ToString().TrimEnd();
    }

    private static string BuildToDocBody(RecordModel model)
    {
        var lines = new StringBuilder();
        string idExpr = model.KeyProp.HasValue
            ? $"record.{model.KeyProp.Value.Name}?.ToString() ?? string.Empty"
            : "string.Empty";

        string fieldsExpr = GeneratorMetadataNames.NullLiteral;
        if (model.DataProps.Count > 0)
        {
            var fieldEntries = new StringBuilder();
            foreach (var dataProp in model.DataProps)
            {
                fieldEntries.AppendLine($"                {{ \"{dataProp.StorageName}\", (object?)record.{dataProp.Name}! }},");
            }

            fieldsExpr = $$"""
new Dictionary<string, object>
            {
{{fieldEntries.ToString().TrimEnd(',', '\r', '\n')}}
            }
""";
        }

        string denseExpr = GeneratorMetadataNames.NullLiteral;
        if (model.VectorProp.HasValue)
        {
            var vector = model.VectorProp.Value;
            denseExpr = $$"""
new Dictionary<string, ReadOnlyMemory<float>>
            {
                { "{{vector.StorageName}}", record.{{vector.Name}} }
            }
""";
        }

        lines.AppendLine($"            return ZVecDoc.Create({idExpr}, {denseExpr}, sparseVectors: null, fields: {fieldsExpr});");
        return lines.ToString().TrimEnd();
    }

    private static string BuildFromDocBody(RecordModel model)
    {
        var lines = new StringBuilder();
        if (model.KeyProp.HasValue)
        {
            var key = model.KeyProp.Value;
            if (key.FullyQualifiedType is GeneratorMetadataNames.GlobalSystemStringType
                or GeneratorMetadataNames.StringTypeAlias)
            {
                lines.AppendLine($"            record.{key.Name} = doc.Id;");
            }
            else
            {
                lines.AppendLine($"            record.{key.Name} = ({key.FullyQualifiedType})Convert.ChangeType(doc.Id, typeof({key.FullyQualifiedType}))!;");
            }
        }

        foreach (var dataProp in model.DataProps)
        {
            lines.AppendLine($$"""
            if (doc.Fields.TryGetValue("{{dataProp.StorageName}}", out var {{dataProp.Name}}Val) && {{dataProp.Name}}Val != null)
                record.{{dataProp.Name}} = ({{dataProp.FullyQualifiedType}}){{dataProp.Name}}Val;
""");
        }

        if (model.VectorProp.HasValue)
        {
            var vector = model.VectorProp.Value;
            lines.AppendLine($$"""
            if (doc.DenseVectors.TryGetValue("{{vector.StorageName}}", out var {{vector.Name}}Dense))
                record.{{vector.Name}} = {{vector.Name}}Dense;
""");
        }

        return lines.ToString().TrimEnd();
    }

    private static string MapSpecialTypeToZVecDataType(SpecialType specialType, string fullyQualifiedType)
    {
        return specialType switch
        {
            SpecialType.System_String => "ZVecDataType.String",
            SpecialType.System_Boolean => "ZVecDataType.Bool",
            SpecialType.System_Int32 => "ZVecDataType.Int32",
            SpecialType.System_Int64 => "ZVecDataType.Int64",
            SpecialType.System_UInt32 => "ZVecDataType.UInt32",
            SpecialType.System_UInt64 => "ZVecDataType.UInt64",
            SpecialType.System_Single => "ZVecDataType.Float",
            SpecialType.System_Double => "ZVecDataType.Double",
            _ => fullyQualifiedType switch
            {
                GeneratorMetadataNames.GlobalSystemGuidType => "ZVecDataType.String",
                _ => "ZVecDataType.String"
            }
        };
    }
}
