using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ZVec.Extensions.VectorData.SourceGenerator;

/// <summary>
/// Incremental Roslyn Source Generator that produces zero-reflection static metadata mappers
/// for POCOs annotated with Microsoft.Extensions.VectorData attributes.
/// </summary>
/// <remarks>
/// <code>
/// ┌─────────────────────────────────────────────────────────────┐
/// │               Annotated [VectorStore] POCO                  │
/// ├─────────────────────────────────────────────────────────────┤
/// │            ZVecRecordMetadataGenerator (Roslyn SG)          │
/// ├─────────────────────────────────────────────────────────────┤
/// │   Emits &lt;Class&gt;ZVecMetadataMapper.g.cs (0-Reflection AOT)  │
/// └─────────────────────────────────────────────────────────────┘
/// </code>
/// </remarks>
[Generator]
public sealed class ZVecRecordMetadataGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidateClass(s),
                transform: static (ctx, _) => GetClassForGeneration(ctx))
            .Where(static m => m is not null);

        context.RegisterSourceOutput(classDeclarations, static (spc, source) =>
        {
            if (source != null)
            {
                GenerateSource(spc, source.Value);
            }
        });
    }

    private static bool IsCandidateClass(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDeclaration && classDeclaration.AttributeLists.Count > 0
               || node is ClassDeclarationSyntax cds && cds.Members.OfType<PropertyDeclarationSyntax>().Any(p => p.AttributeLists.Count > 0);
    }

    private static RecordModel? GetClassForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

        if (symbol == null) return null;

        var properties = symbol.GetMembers().OfType<IPropertySymbol>().ToList();
        bool hasVectorDataAttributes = properties.Any(p =>
            p.GetAttributes().Any(a => a.AttributeClass?.Name.Contains("VectorStore") == true));

        if (!hasVectorDataAttributes) return null;

        // Skip POCOs declared in the global namespace — file-scoped namespace declaration
        // would emit invalid C# ('namespace <global namespace>;').
        if (symbol.ContainingNamespace.IsGlobalNamespace) return null;

        string namespaceName = symbol.ContainingNamespace.ToDisplayString();
        string className = symbol.Name;

        return new RecordModel(namespaceName, className);
    }

    private static void GenerateSource(SourceProductionContext context, RecordModel model)
    {
        string source = $@"// <auto-generated/>
#nullable enable

using System;
using Microsoft.Extensions.VectorData;

namespace {model.NamespaceName};

/// <summary>
/// Generated zero-reflection static metadata mapper for <see cref=""{model.ClassName}""/>.
/// </summary>
public static class {model.ClassName}ZVecMetadataMapper
{{
    /// <summary>
    /// Gets the static VectorStoreCollectionDefinition for <see cref=""{model.ClassName}""/>.
    /// </summary>
    public static VectorStoreCollectionDefinition Definition {{ get; }} = new VectorStoreCollectionDefinition();
}}
";

        context.AddSource($"{model.ClassName}ZVecMetadataMapper.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private readonly struct RecordModel
    {
        public RecordModel(string namespaceName, string className)
        {
            NamespaceName = namespaceName;
            ClassName = className;
        }

        public string NamespaceName { get; }
        public string ClassName { get; }
    }
}
